# Web暴露端口
server:
  port: 9001

# spring 相关配置
spring:
  application:
    name: customer

# nacos 相关配置
nacos:
  service-address: 127.0.0.1
  port: 8848

# dubbo 相关配置
dubbo:
  application:
    name: ${spring.application.name}
  # 服务消费端配置
  consumer:
    # 超时时间，单位：毫秒
    timeout: 5000
  # 注册中心 采用nacos
  registry:
    address: nacos://${nacos.service-address}:${nacos.port}
