# Web暴露端口
server:
  port: 9000

# spring 相关配置
spring:
  application:
    name: provider

# nacos 相关配置
nacos:
  service-address: 127.0.0.1
  port: 8848

# dubbo 相关配置
dubbo:
  application:
    name: ${spring.application.name}
  # 服务提供端配置
  provider:
    # 超时时间，单位：毫秒
    timeout: 6000
  # 扫描带有@DubboService注解的包
  scan:
    base-packages: com.teacherblitz.service.impl
  # dubbo协议暴露的端口
  protocol:
    name: dubbo
    port: 20880
  # 注册地址
  registry:
    address: nacos://${nacos.service-address}:${nacos.port}