server:
  port: 20000

spring:
  application:
    name: provider
dubbo:
  application:
    name: ${spring.application.name}
  protocol:
    name: dubbo
    port: 20880
  registry: spring-cloud:127.0.0.1:8848
  scan:
    base-packages: com.teacherblitz.service.impl
  cloud:
    subscribed-services: '/'